/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import java.util.Scanner;

public class App {

  public static void main(String[] args) {

    String ANSI_CLEAR = "\033[0m";
    String ANSI_BOLD_RED = "\033[1;31m";
    String ANSI_RED = "\033[0;31m";

    String[][] menuArray = {
        {ANSI_RED + "[과제관리시스템]" + ANSI_CLEAR, ""},
        {"1.과제", "과제입니다."},
        {"2.게시글", "게시글입니다."},
        {"3.도움말", "도움말입니다."},
        {"4.종료", ANSI_BOLD_RED + "종료합니다." + ANSI_CLEAR}
    };

    for (String[] value : menuArray) {
      System.out.println(value[0]);
    }

    Scanner scan = new Scanner(System.in);

    loop:
    while (true) {
      System.out.print(">");
      String menuInput = scan.nextLine();

      switch (menuInput) {
        case "1":
          System.out.println(menuArray[1][1]);
          break;
        case "2":
          System.out.println(menuArray[2][1]);
          break;
        case "3":
          System.out.println(menuArray[3][1]);
          break;
        case "4":
          System.out.println(menuArray[4][1]);
          break loop;
        case "menu":
          for (String[] strings : menuArray) {
            System.out.println(strings[0]);
          }
          break;
        default:
          System.out.println("메뉴 번호가 옳지 않습니다.");
      }
    }
    scan.close();
  }
}